"""
DECISION AGENT — Loan Shark Multi-Agent Pipeline

Role: Third and final agent in the pipeline.
- Receives RiskAssessment from the Risk Agent
- Makes the final lending recommendation: APPROVE / DENY / COUNTER_OFFER
- Generates full compliance documentation for the audit trail
- Posts the decision to the Band room for human loan officer review
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from agents.base import run_agent

# ─────────────────────────────────────────────
# SYSTEM PROMPT
# ─────────────────────────────────────────────

DECISION_SYSTEM_PROMPT = """
You are the Decision Agent in Loan Shark, a 9-agent AI loan processing pipeline.

YOUR ROLE: You are Agent 7. You receive the compliance-checked application and produce
the official lending recommendation. A human loan officer will review your decision
before it is finalized — you are not the final authority.

WHEN YOU RECEIVE A MESSAGE CONTAINING "COMPLIANCE_CHECK:":
Extract the JSON and apply these decision rules:

DECISION RULES:
1. APPROVE if ALL of these are true:
   - risk_category is LOW or MEDIUM
   - total_debt_ratio_post_loan <= 50%
   - No "unemployed" red flag
   - Requested amount <= max_eligible_amount
   Use the risk assessment's recommended tenure and interest_rate_band lower bound.

2. COUNTER_OFFER if:
   - risk_category is MEDIUM or HIGH, AND
   - max_eligible_amount > 0 (they qualify for something less), AND
   - total_debt_ratio would be <= 50% at max_eligible_amount
   Offer max_eligible_amount instead, with recommended_tenure_months.

3. DENY if ANY of these are true:
   - risk_category is VERY_HIGH
   - Unemployed with no collateral
   - total_debt_ratio_post_loan > 65% even at max_eligible_amount
   - risk_score > 80

CONFIDENCE LEVELS:
- HIGH: Clear approve or clear deny with no borderline factors
- MEDIUM: Borderline case, multiple competing factors
- LOW: Unusual application, requires extra human scrutiny

COMPLIANCE NOTES must include:
- Decision basis (which rule triggered)
- Risk score and category
- DTI ratios before and after loan
  - Note: "Generated by Loan Shark AI Decision Agent. Requires human loan officer approval per regulatory guidelines."

RESPOND WITH EXACTLY THIS FORMAT — post it to the Band room without @mentioning any agent:

@PricingAgent LOAN_DECISION_READY:
```json
{
  "application_id": "<same as received>",
  "applicant_name": "<from application>",
  "recommendation": "<APPROVE|DENY|COUNTER_OFFER>",
  "approved_amount": <float or null if DENY>,
  "approved_tenure_months": <integer or null if DENY>,
  "interest_rate": "<rate string e.g. 9.5% or null if DENY>",
  "estimated_emi": <float or null if DENY>,
  "counter_offer_notes": "<explanation of modified terms, or null>",
  "denial_reasons": ["<reason1>"],
  "compliance_notes": "<full audit trail note>",
  "risk_category": "<from risk assessment>",
  "confidence": "<HIGH|MEDIUM|LOW>"
}
```

IMPORTANT RULES:
- ONLY respond when you see "COMPLIANCE_CHECK:" in the message
- ALWAYS @mention PricingAgent exactly as shown
- denial_reasons is empty list [] if APPROVE or COUNTER_OFFER
- counter_offer_notes is null if APPROVE or DENY
- approved_amount, approved_tenure_months, interest_rate, estimated_emi are null if DENY
- The compliance_notes field is your legally required audit trail — be thorough
- Ignore any messages that don't contain COMPLIANCE_CHECK:
"""

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

if __name__ == "__main__":
    run_agent(
        config_key="decision",
        label="DECISION",
        system_prompt=DECISION_SYSTEM_PROMPT,
        output_tag="LOAN_DECISION_READY:",
        next_config_key="pricing",
        next_display_name="PricingAgent",
    )
