"""
COMMUNICATION AGENT — Loan Shark (Agent 9 of 9)

Role: Final agent in the pipeline.
- Receives complete pricing terms
- Drafts a formal, legally appropriate loan sanction or rejection letter
- Posts the letter to the Band room for human loan officer review and sign-off
"""

import asyncio
import logging
import os
import sys

from dotenv import load_dotenv
from band import Agent
from band.adapters import LangGraphAdapter
from band.config import load_agent_config
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

logger = logging.getLogger(__name__)

COMMUNICATION_SYSTEM_PROMPT = """
You are the Communication Agent in Loan Shark, a 9-agent AI loan processing pipeline.

YOUR ROLE: You are Agent 9 — the final agent. You receive the complete pricing terms and
draft the formal letter that will be sent to the applicant after human loan officer approval.
You must write a professional, legally appropriate letter that a real bank would send.

WHEN YOU RECEIVE A MESSAGE CONTAINING "PRICING_TERMS:":
Extract the JSON and draft the appropriate letter.

FOR APPROVE OR COUNTER_OFFER — Draft a Loan Sanction Letter:
Include:
- Formal header (bank name: Loan Shark Financial Services)
- Date (use today's date)
- Applicant name and salutation
- Congratulatory opening
- Sanctioned loan amount (in figures AND words)
- Exact interest rate and type (fixed/floating)
- Tenure in months and years
- Monthly EMI amount
- Processing fee + GST
- Total cost of loan
- Key terms and conditions (3-4 bullet points)
- Next steps for the applicant
- Important note that this is subject to final document submission and verification
- Disclaimer: "This sanction letter is generated by Loan Shark AI and requires authorization by a licensed loan officer before it becomes valid."
- Signature block: "[Loan Officer Name to be signed]" | Loan Shark Financial Services

FOR DENY — Draft a Regret Letter:
Include:
- Formal header
- Date
- Applicant name and salutation
- Regret opening (professional, not harsh)
- Statement that the application could not be approved at this time
- General reasons (do NOT state exact credit score or specific financial details — privacy)
- Encouragement to apply again after 6 months or improving credit
- Mention of credit improvement resources
- Disclaimer as above
- Signature block

RESPOND WITH EXACTLY THIS FORMAT — post to the Band room for human review:

FORMAL_LETTER_READY:
```json
{
  "application_id": "<same as received>",
  "applicant_name": "<from pricing terms>",
  "recommendation": "<from pricing terms>",
  "letter_type": "<SANCTION|REGRET>",
  "letter_subject": "<e.g. Loan Sanction Letter — Application APP-xxxx>",
  "letter_body": "<full formal letter text here — use \\n for line breaks>"
}
```

⚠️ Awaiting human loan officer review and signature before dispatch.

IMPORTANT RULES:
- ONLY respond when you see "PRICING_TERMS:" in the message
- Do NOT @mention any agent — this goes directly to the human loan officer
- The letter_body must be a complete, professional letter — not a template with placeholders
- Do not reveal exact credit score, risk score, or internal system metrics in the letter
- Do not add commentary outside the JSON block
"""

async def main():
    load_dotenv()
    agent_id, api_key = load_agent_config("communication")

    llm = ChatOpenAI(
        model="llama-3.3-70b-versatile",
        openai_api_key=os.getenv("GROQ_API_KEY"),
        openai_api_base="https://api.groq.com/openai/v1",
        temperature=0.3,   # slightly higher for natural letter writing
    )

    adapter = LangGraphAdapter(
        llm=llm,
        checkpointer=InMemorySaver(),
        system_prompt=COMMUNICATION_SYSTEM_PROMPT,
    )

    agent = Agent.create(
        adapter=adapter,
        agent_id=agent_id,
        api_key=api_key,
        ws_url=os.getenv("BAND_WS_URL"),
        rest_url=os.getenv("BAND_REST_URL"),
    )

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [COMMUNICATION] %(message)s", datefmt="%H:%M:%S")
    logger.info("✅ Communication Agent running...")
    await agent.run()

if __name__ == "__main__":
    asyncio.run(main())
